version: 2.1

jobs:
  build:
    working_directory: ~/circleci-caver-java
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout

      - run:
          name: Pull and tag Klaytn image
          command: |
            docker pull kjhman21/dev:v1.0.0
            docker image tag kjhman21/dev:v1.0.0 klaytn

      - run:
          name: Start test network
          working_directory: .circleci/images/primary
          command: docker-compose up -d

      - run:
          name: Build and test
          command: |
            ./gradlew clean
            ./gradlew build --scan --debug

  deploy:
    working_directory: ~/circleci-caver-java
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: ./gradlew release

workflows:
  version: 2.1
  caver-java-ci:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - hold